spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_category_service
    username: root
    password: root

  liquibase:
    change-log: db.changelog/migration.xml

jwt:
  secret: 55644fgf$%&jh
  expiration: 450000






